### ISSUE TITLE
Gitlab runner attempts to create .gitlab-runner folder in / instead of /home/gitlab-runner

### ISSUE THREAD

**Issue by voor** [bitnami/bitnami-docker-gitlab-runner#1]
### Name and Version

registry.pivotal.io/tac-federal-apple/containers/ubuntu-custom/gitlab-runner:14

### What steps will reproduce the bug?

Using the gitlab runner helm template, change container over to bitnami based container.  You also need to change the security context to 1001, since that is the user ID instead of 999 for the Ubuntu container.

### What is the expected behavior?

After successful registration it should use the working directory specified as `/home/gitlab-runner` when it starts the runner here:

```
    # Start the runner
    exec /entrypoint run --user=gitlab-runner \
      --working-directory=/home/gitlab-runner
```

### What do you see instead?

```
Registration attempt 30 of 30
 09:16:20.35 
 09:16:20.35 Welcome to the Bitnami gitlab-runner container
 09:16:20.35 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-gitlab-runner
 09:16:20.35 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-gitlab-runner/issues
 09:16:20.35 
 09:16:20.36 INFO  ==> Configuring libnss_wrapper
Runtime platform                                    arch=amd64 os=linux pid=870 revision=f761588f version=14.10.1
WARNING: Running in user-mode.                     
WARNING: The user-mode requires you to manually start builds processing: 
WARNING: $ gitlab-runner run                       
WARNING: Use sudo for system-mode:                 
WARNING: $ sudo gitlab-runner...                   
                                                   
Registering runner... succeeded                     runner=REMOVED
PANIC: mkdir /.gitlab-runner: permission denied    
Unregistering runner from GitLab succeeded          runner=REMOVED

```
Note that it's trying to make the directory in `/` instead of `/home/gitlab-runner`

**Comment by migruiz4** [comment]
Hi @voor,

Sorry for the late response. I currently lack the resources to reproduce the issue, but maybe setting the securityContext as it follows help solve the issue:

```
securityContext:
  runAsUser: 1001
  fsGroup: 1001
```

I found these issues with similar output that may be related, both referencing ` /.gitlab-runner` instead of `/home/gitlab-runner`: 
- https://gitlab.com/gitlab-org/charts/gitlab-runner/-/issues/299
- https://gitlab.com/gitlab-org/charts/gitlab-runner/-/merge_requests/215

**Comment by voor** [comment]
I was able to get around this issue by changing the working directory to just `/`

```
#@overlay/match by="name", when=1
- mountPath: /.gitlab-runner
  name: etc-gitlab-runner
#@overlay/match by="name", when=1
- mountPath: /.gitlab-runner/certs/
  name: custom-certs
```
and changing:
`--working-directory=/home/gitlab-runner` to `--working-directory=/`

I am currently using your recommended runAsUser and fsGroup, but that does not fix the problem.

**Comment by voor** [comment]
Okay, I reverted to the upstream helper to get past https://github.com/bitnami/bitnami-docker-gitlab-runner-helper/issues/1 issue, turns out the permission failed isn't related to that one, it's still this one, in particular the fact the working directory becomes / inside the container you're unable to make any folders or mount anything, since `/` would wipe out the entire container.

```
error: could not lock config file //.gitconfig: Permission denied
```

**Comment by migruiz4** [comment]
Sorry for the late response @voor,

Could you please share a sanitized version of the `values.yaml` and helm install command you used to deploy the `gitlab-runner` chart?

That would help us troubleshoot this issue
